# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c99d23de8a8b57edbb7753a39a006d4deb7026f8928f4c4c75731f7437f372f5d490f6b66e8b84509aaa22359c8d3cef5548175a28b45d440a513568fac0d5f

test:
  secret_key_base: 0bb50dd6b3fab45196511fec5589f653dfd8448506a71af4c6ab073169032bbf46523d1c97508d5fbad1e55b672531649778de0ff728cdc936efd76604a827bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
